// Some boilplate code generated by AI. Needs to be partially reworked. Will make changes once we have data.

document.addEventListener('DOMContentLoaded', function() {
    // Configuration
    const TOTAL_IMAGES = 60;
    const QUIZ_SIZE = 10;
    
    // Elements
    const welcomeScreen = document.getElementById('welcome-screen');
    const quizScreen = document.getElementById('quiz-screen');
    const demographicsScreen = document.getElementById('demographics-screen');
    const resultsScreen = document.getElementById('results-screen');
    const startButton = document.getElementById('start-quiz');
    const currentImage = document.getElementById('current-image');
    const btnAI = document.getElementById('btn-ai');
    const btnReal = document.getElementById('btn-real');
    const questionCounter = document.getElementById('question-counter');
    const progressBar = document.getElementById('progress-bar');
    const demographicsForm = document.getElementById('demographics-form');
    
    // Quiz state
    let selectedImages = [];
    let currentQuestionIndex = 0;
    let userResponses = [];
    
    // Google Form settings
    const GOOGLE_FORM_URL = '';
    
    // Event listeners
    startButton.addEventListener('click', startQuiz);
    btnAI.addEventListener('click', () => recordAnswer(true));
    btnReal.addEventListener('click', () => recordAnswer(false));
    demographicsForm.addEventListener('submit', submitResults);
    
    // Functions
    function startQuiz() {
        selectedImages = selectRandomImages(TOTAL_IMAGES, QUIZ_SIZE);
        welcomeScreen.classList.add('d-none');
        quizScreen.classList.remove('d-none');
        loadQuestion(0);
    }
    
    function selectRandomImages(totalCount, selectCount) {
        let allIndices = Array.from({length: totalCount}, (_, i) => i + 1);
        let selected = [];
        
        for (let i = 0; i < selectCount; i++) {
            const randomIndex = Math.floor(Math.random() * allIndices.length);
            selected.push(allIndices.splice(randomIndex, 1)[0]);
        }
        
        return selected;
    }
    
    function loadQuestion(index) {
        if (index >= selectedImages.length) {
            showDemographicsScreen();
            return;
        }
        
        // Reset button selection
        btnAI.classList.remove('selected');
        btnReal.classList.remove('selected');
        
        // Update UI
        currentQuestionIndex = index;
        const imageId = selectedImages[index];
        currentImage.src = `images/img${imageId}.jpg`;
        questionCounter.textContent = `Question ${index + 1} of ${QUIZ_SIZE}`;
        progressBar.style.width = `${((index + 1) / QUIZ_SIZE) * 100}%`;
    }
    
    function recordAnswer(isAI) {
        // Highlight selected button
        btnAI.classList.toggle('selected', isAI);
        btnReal.classList.toggle('selected', !isAI);
        
        const imageId = selectedImages[currentQuestionIndex];
        const isCorrect = (isAI === true);
        
        userResponses[imageId] = isCorrect ? 2 : 1;
        
        setTimeout(() => {
            loadQuestion(currentQuestionIndex + 1);
        }, 200);
    }
    
    function showDemographicsScreen() {
        quizScreen.classList.add('d-none');
        demographicsScreen.classList.remove('d-none');
    }
    
    function submitResults(e) {
        e.preventDefault();
        
        const form = document.createElement('form');
        form.method = 'POST';
        form.action = GOOGLE_FORM_URL;
        form.target = '_blank';
        
        // Add demographic information
        const ageInput = createHiddenInput('entry.XXXXX', document.getElementById('age').value); // Replace XXXXX with actual form field ID
        const genderInput = createHiddenInput('entry.XXXXX', document.getElementById('gender').value); // Replace XXXXX with actual form field ID
        const occupationInput = createHiddenInput('entry.XXXXX', document.getElementById('occupation').value);
        const experienceInput = createHiddenInput('entry.XXXXX', document.getElementById('experience').value); // Replace XXXXX with actual form field ID
        
        form.appendChild(ageInput);
        form.appendChild(genderInput);
        form.appendChild(occupationInput);
        form.appendChild(experienceInput);
        
        // Add responses for all 60 images
        for (let i = 1; i <= TOTAL_IMAGES; i++) {
            // 0 = not shown, 1 = incorrect, 2 = correct
            const value = userResponses[i] !== undefined ? userResponses[i] : 0;
            const input = createHiddenInput(`entry.XXXXX_${i}`, value); // Replace XXXXX with actual form field ID
            form.appendChild(input);
        }
        
        // Submit form
        document.body.appendChild(form);
        form.submit();
        document.body.removeChild(form);
        
        // Show results screen
        demographicsScreen.classList.add('d-none');
        resultsScreen.classList.remove('d-none');
    }
    
    function createHiddenInput(name, value) {
        const input = document.createElement('input');
        input.type = 'hidden';
        input.name = name;
        input.value = value;
        return input;
    }
});
